### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by popakrt** [bs-community/blessing-skin-plugins#10]
建议增加对[phpbb](https://www.phpbbchinese.com/)论坛程序进行数据对接，让玩家使用这个论坛系统账号密码登录皮肤站，毕竟这个论坛系统比Discuz开放，他用的是GNU通用公共许可协议。

**Comment by printempw** [comment]
之后有时间的话我会测试一下对 phpbb 的支持，感谢建议

**Comment by g-plane** [comment]
@popakrt 能提供 phpbb 的密码加密算法吗？

**Comment by g-plane** [comment]
长时间未收到回复，先关闭此 issue。如果有需要可以继续讨论。
