### ISSUE TITLE
[yggdrasil-api] 游戏启动抛 AuthenticationUnavailableException, 无法进入服务器

### ISSUE THREAD

**Issue by WindLeaf233** [bs-community/blessing-skin-plugins#100]
## 问题描述

玩家无法进入通过 yggdrasil api 验证的服务器. 但除了这个玩家, 其他的玩家都可以进入.

## 运行环境

- Blessing Skin 版本: 6.0.0-beta.2
- Blessing Skin 用的 PHP 版本: 7.4.15
- Blessing Skin 的 Web 服务软件: Apache
- 游戏版本: 1.16.5
- Yggdrasil Api 插件版本: 5.1.2

## 日志

[客户端日志](https://paste.ubuntu.com/p/xMhTXZSrbk/)
[服务端日志 (部分)](https://paste.ubuntu.com/p/jnwmTYkYgx/)

## 重现步骤

1. 启动 HMCL, 选中皮肤站账户
2. 点击启动
3. 进入服务器
4. 显示 `登入失败: 身份验证目前正在停机维护`

**Comment by Asnxthaony** [comment]
**请等待「Yggdrasil Api」和「authlib-injector」更新。**

由于 Mojang 在 Minecraft: Java Edition 1.16.5 加入了社交互动界面(Social Interactions screen)，此版本使用的 authlib-2.1.28 会向 `api.minecraftservices.com` 查询用户的社交权限(Privileges)，若无查询结果，则会抛出 `AuthenticationUnavailableException` 异常，导致登录失败。

```java
private void checkPrivileges() throws AuthenticationException {
    PrivilegesResponse response = this.authenticationService.makeRequest(this.routePrivileges, null, PrivilegesResponse.class, "Bearer " + this.accessToken);
    if (response == null) {
        throw new AuthenticationUnavailableException();
    }
    this.chatAllowed = response.getPrivileges().getOnlineChat().isEnabled();
    this.serversAllowed = response.getPrivileges().getMultiplayerServer().isEnabled();
    this.realmsAllowed = response.getPrivileges().getMultiplayerRealms().isEnabled();
}
```

**Comment by yushijinhun** [comment]
> **请等待「Yggdrasil Api」和「authlib-injector」更新。**
> 
> 由于 Mojang 在 Minecraft: Java Edition 1.16.5 加入了社交互动界面(Social Interactions screen)，此版本使用的 authlib-2.1.28 会向 `api.minecraftservices.com` 查询用户的社交权限(Privileges)，若无查询结果，则会抛出 `AuthenticationUnavailableException` 异常，导致登录失败。
> 
> ```java
> private void checkPrivileges() throws AuthenticationException {
>     PrivilegesResponse response = this.authenticationService.makeRequest(this.routePrivileges, null, PrivilegesResponse.class, "Bearer " + this.accessToken);
>     if (response == null) {
>         throw new AuthenticationUnavailableException();
>     }
>     this.chatAllowed = response.getPrivileges().getOnlineChat().isEnabled();
>     this.serversAllowed = response.getPrivileges().getMultiplayerServer().isEnabled();
>     this.realmsAllowed = response.getPrivileges().getMultiplayerRealms().isEnabled();
> }
> ```

抛 AuthenticationUnavailableException 并不会导致无法登录，你可以自己用 1.16.5 测试下。

**Comment by Asnxthaony** [comment]
抱歉，结论有误。

本人所使用的客户端，因部分原因，使用了早期版本的 authlib-injector。

如果你正在使用 HMCL 启动器，可以通过删除 `%appdata%\.hmcl\authlib-injector.jar` 尝试更新 authlib injector

**Comment by WindLeaf233** [comment]
> 抱歉，结论有误。
> 
> 本人所使用的客户端，因部分原因，使用了早期版本的 authlib-injector。
> 
> 如果你正在使用 HMCL 启动器，可以通过删除 `%appdata%\.hmcl\authlib-injector.jar` 尝试更新 authlib injector

没有用, 还是无法进入服务器, 依旧提示 `登入失败: 身份验证目前正在停机维护`.
客户端日志 & 服务端日志与上面的那个一样.

**Comment by WindLeaf233** [comment]
我发现 authlib-injector.log 有一段错误如下:
[Pastebin](https://paste.ubuntu.com/p/qz9zp5mPNQ/)

我认为我该将此错误报告至 authlib-injector issue

**Comment by WindLeaf233** [comment]
[https://github.com/yushijinhun/authlib-injector/issues/119](https://github.com/yushijinhun/authlib-injector/issues/119), 已解决.
原来是 TLS 证书或 Java 版本的问题, 感谢回复!
