### ISSUE TITLE
[bug]在配置文件开启 Yggdrasil 日志显示后全站崩溃（白屏，毫无显示）

### ISSUE THREAD

**Issue by DreamUniverse843** [bs-community/blessing-skin-plugins#101]
## The Problem 问题描述

遵照 https://blessing.netlify.app/yggdrasil-api/ 在 .env 开启 Yggdrasil 记录配置后全站白屏，毫无显示

## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):6.0.0-beta2
- PHP 版本 (Version of PHP):7.4.3
- Apache / Nginx:Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):全站任何链接均白屏

## Error Message 错误信息

什么也没有，就一个完全雪白的屏幕（debug 都没有用）

## Steps to Reproduce 重现步骤

在配置文件中最后一行添加 `YGG_VERBOSE_LOG=true` 后全站任何链接均白屏。

**Comment by g-plane** [comment]
请检查 storage/logs 目录的权限。

**Comment by DreamUniverse843** [comment]
目录的权限没有问题。
因为源站在 5.2.0 升级前的 Yggdrasil 日志是正常记录的，升级后出现问题。

**Comment by g-plane** [comment]
仅仅是开启而没有进行其它操作？因为我这边没遇到这个问题。

**Comment by DreamUniverse843** [comment]
抱歉，这个 Issue 可能提的太久了/捂脸
之前升级到 6.0.0-beta 2 出现的这个问题，而贵方已在 6.0.0-beta 3 修复了这个问题。
此问题已经升级解决，即便如此也感谢您的关注！

**Comment by g-plane** [comment]
也很抱歉我们这么晚才发布 beta 3。
