### ISSUE TITLE
有关外置问题：在群组服上（不管是bungeecord还是velocity）用authlib-injector指向我的皮肤站时，玩家无法登录

### ISSUE THREAD

**Issue by ThreeIce** [bs-community/blessing-skin-plugins#102]
在群组服上（不管是bungeecord还是velocity）用authlib-injector指向我的皮肤站时，玩家都登录不进去，前者先是显示通讯加密中然后超时，后者则直接连接不上，单纯paper可以，指向目标改为littleskin时，可以连接只是显示无效会话（这个问题遇到很多次，没有发现规律，不过服务端应该是连上littleskin了，也就是说似乎只有在我的皮肤站有这个问题），观察过后台日志，authlib-injector似乎少了几个Transformed xx的输出。
皮肤站地址：https://mc.threeice.com:8083/
如能尽快帮忙将感激不尽，急
接下来附上日志（BungeeCord）
[MCSMANAGER] [ 2021/4/5 3:39:11 ]: 服务端 lobby 执行开启命令. 
[MCSMANAGER] -------------------------------------------------------------- 
[authlib-injector] [INFO] Logging file: /opt/MCSManager/server/server_core/lobby/authlib-injector.log
[authlib-injector] [INFO] Version: 1.1.35
[authlib-injector] [INFO] Authentication server: https://mc.threeice.com:8083/api/yggdrasil
03:39:12 [INFO] Using mbed TLS based native cipher.
03:39:12 [INFO] Using zlib based native compressor.
03:39:12 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:d49e97c:1575
[authlib-injector] [INFO] Httpd is running on port 54013
[authlib-injector] [INFO] Transformed [net.md_5.bungee.connection.InitialHandler] with [Constant URL Transformer]
03:39:12 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
03:39:12 [INFO] Epoll is working, utilising it!
03:39:13 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
03:39:13 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
03:39:13 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
03:39:13 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
03:39:13 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
03:39:13 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
03:39:13 [INFO] Loaded plugin Geyser-BungeeCord version 1.2.1-SNAPSHOT by GeyserMC
03:39:13 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:13 [INFO] Loaded plugin cmd_find version git:cmd_find:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:13 [INFO] [floodgate-bungee] Loading Floodgate linked player database...
03:39:13 [INFO] Loaded plugin floodgate-bungee version 1.0-SNAPSHOT by GeyserMC
03:39:13 [INFO] Loaded plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:13 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:13 [INFO] Loaded plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:13 [INFO] Loaded plugin cmd_list version git:cmd_list:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:13 [WARNING] Forced host server pvp is not defined
03:39:13 [WARNING] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
03:39:13 [INFO] [Geyser-BungeeCord] ******************************************
03:39:13 [INFO] [Geyser-BungeeCord] 
03:39:13 [INFO] [Geyser-BungeeCord] Loading Geyser version 1.2.1-SNAPSHOT (git-master-4734ce2)
03:39:13 [INFO] [Geyser-BungeeCord] 
03:39:13 [INFO] [Geyser-BungeeCord] ******************************************
[ SYSTEM ] 正在监听服务端日志输出.
03:39:20 [INFO] [Geyser-BungeeCord] Started Geyser on 0.0.0.0:50753
03:39:20 [INFO] [Geyser-BungeeCord] Done (6.6s)! Run /geyser help for help!
03:39:20 [INFO] Enabled plugin Geyser-BungeeCord version 1.2.1-SNAPSHOT by GeyserMC
03:39:20 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:20 [INFO] Enabled plugin cmd_find version git:cmd_find:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:20 [INFO] Enabled plugin floodgate-bungee version 1.0-SNAPSHOT by GeyserMC
03:39:20 [INFO] Enabled plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:20 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:20 [INFO] Enabled plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC
03:39:20 [INFO] Enabled plugin cmd_list version git:cmd_list:1.16-R0.5-SNAPSHOT:d49e97c:1575 by SpigotMC

**Comment by Asnxthaony** [comment]
更新 authlib-injector 至 v1.1.37

https://github.com/yushijinhun/authlib-injector/issues/108
