### ISSUE TITLE
Yggdrasil API无法使用？

### ISSUE THREAD

**Issue by Yuii-guoguo** [bs-community/blessing-skin-plugins#104]
新搭建的皮肤站使用Yggdrasil API插件无法用HMCL-3.3.188连接.
https://skin.w41k3r.net/api/yggdrasil
用http或https均无法添加,提示无法连接认证服务器,其他皮肤站可以正常添加.

**Comment by Asnxthaony** [comment]
证书链不完整

https://blog.myssl.com/faq-miss-ca-certificate/
