### ISSUE TITLE
[mojang-verification] 建议支持微软正版绑定

### ISSUE THREAD

**Issue by PAKingdom** [bs-community/blessing-skin-plugins#106]
建议支持微软正版绑定

**Comment by LiamSho** [comment]
Mojang已宣布开始迁移至微软账户（现在还只是小部分），微软账号正版绑定功能应该提高优先级了？

**Comment by Yurinann** [comment]
> Mojang已宣布开始迁移至微软账户（现在还只是小部分），微软账号正版绑定功能应该提高优先级了？

是的，9/10 时Mojang已经向所有已购买游戏的Mojang账号发出迁移权限：https://www.mcbbs.net/thread-1259670-1-4.html
