### ISSUE TITLE
Yggdrasil API不能用于V5?

### ISSUE THREAD

**Issue by NiuBoss123** [bs-community/blessing-skin-plugins#107]
Yggdrasil API不能用于V5?
如图：
`<img src="http://image.starsource.top:8022/images/2021/06/17/QQ20210617212927.png" alt="QQ20210617212927.png" border="0" />`
另发送我遇到过的一个问题(在V6-BETA2启用Yggdrasil API时候遇到的)：
`<img src="http://image.starsource.top:8022/images/2021/06/17/QQ20210617213611.png" alt="QQ20210617213611.png" border="0" />`

**Comment by g-plane** [comment]
不能，如果需要在 v5 上使用，请安装旧版的 yggdrasil-api 插件。

**Comment by NiuBoss123** [comment]
非常感谢，也提个意见：希望在插件市场补充旧版本的插件
