### ISSUE TITLE
无法解析认证服务器响应

### ISSUE THREAD

**Issue by Bearlele** [bs-community/blessing-skin-plugins#108]
内网搭建的 通过url可以访问api 用户也是存在的 添加验证服务器能获取到站点标题但是在启动器里新建账户却提示 无法解析认证服务器响应

**Comment by Bearlele** [comment]
> 日志里报错消息是：
> 
> ```
> Details: Argument 1 passed to Lcobucci\JWT\Signer\Key\InMemory::plainText() must be of the type string, null given, called in /var/www/public/plugins/yggdrasil-api/src/Controllers/AuthController.php on line 37
> ```

插件报错：The command "jwt:secret" does not exist.
然后我自己去试了下生成加密一样报错：There are no commands defined in the "jwt" namespa
请问有什么解决办法吗 谷歌半天没找到个有用的办法

**Comment by yushijinhun** [comment]
你把 yggdrasil-api 升级到最新版本试试看。这方面我不太懂，可能需要 @g-plane 看下。

**Comment by Bearlele** [comment]
> 你把 yggdrasil-api 升级到最新版本试试看。这方面我不太懂，可能需要 @g-plane 看下。

已经弄好啦

**Comment by 7azisa** [comment]
@Bearlele 怎么解决的嘞，我也碰到一样的问题了

**Comment by Big-Cake-jpg** [comment]
> @Bearlele 怎么解决的嘞，我也碰到一样的问题了

请更新 `Yggdrasil API` 插件到最新版本 5.1.5
