### ISSUE TITLE
authme-integration插件，游戏内Authme注册的玩家无法在皮肤站上登录

### ISSUE THREAD

**Issue by Illusionika** [bs-community/blessing-skin-plugins#110]
皮肤站版本: 5.2.0
插件版本: 2.4.3

在插件README里有这样一句话: 
在 Authme 注册的用户也可以使用游戏角色名与游戏中的密码直接登录皮肤站。

但是并不行，用角色名+密码登录，会提示"用户不存在"
数据库和字段已经改过，没问题。皮肤站的users表已经有了Authme 写的记录。但是players表没有角色

照理说应该在开启这个插件的情况下，在Authme上注册的用户初次登录皮肤站时，验证下"realname"这个字段的角色名是否存在，不存在就新建同名角色， 就像论坛同步插件那样。
(应该还要有个皮肤站上"添加新角色"按钮无法创建realname字段的角色选项之类的功能)

我这里准备把之前Authme注册的玩家迁移到皮肤站上来，这个功能挺需要的..
或者还有别的插件能实现迁移么?(

**Comment by g-plane** [comment]
建议尝试使用 Yggdrasil API。

**Comment by Illusionika** [comment]
额,并不是皮肤站注册游戏里登录,是游戏Authme里注册了,再在皮肤站登录.Yggdrasil API是做不到的.
为什么要这么做.这是历史遗留问题,我也很头大
然后我用了个蠢办法,手动编写了players表和users表....总算是迁过去了
