### ISSUE TITLE
无法解析认证服务器响应，Yggdrasil API 外置登录无法正常工作

### ISSUE THREAD

**Issue by Kuma-Ali** [bs-community/blessing-skin-plugins#114]
## The Problem 问题描述
Yggdrasil API 已经部署，但在返回参数时报错。导致启动器无法解析用户数据。在HMCL新建外置登录账户时会出现该错误。

## Environment 运行环境
- Blessing Skin: v6.0.0-beta.3
- PHP: 7.4
- Nginx: Tengine 2.2
- Microsoft Edge URL:https://accountcenter.miaomc.cn/api/yggdrasil
- 网站套了阿里云的全站加速CDN

## Error Message 错误信息
blessing-skin的log https://pastebin.com/6h5JbiX4
这是HMCL的log https://pastebin.com/JwVFWuZY

## Steps to Reproduce 重现步骤
HMCL新建外置登录账户时会出现该错误

**Comment by k-xuanyu** [comment]
你好，我跟你是同样的问题，我通过尝试得到了解决，下面我说明下我的解决方法：

我尝试的关闭了所有的插件，仅仅留下了，**_Yggdrasil API 插件_** 后问题的到了解决，我正在测试是哪个插件影响了启动器的动如结果，我后续会继续补充这个回答
