### ISSUE TITLE
批量导入皮肤文件失败

### ISSUE THREAD

**Issue by yebanme** [bs-community/blessing-skin-plugins#117]
使用批量导入对皮肤文件进行导入，多次尝试均导入失败
![QQ图片20210806110102](https://user-images.githubusercontent.com/20102749/128449636-8f32f3cf-ed7c-4326-b5ca-e64f57baeedf.png)

测试皮肤文件
![armin-arlert](https://user-images.githubusercontent.com/20102749/128450366-53a73ace-86dd-40f3-9c70-3ed9cd2bb8ff.png)![4-3-2](https://user-images.githubusercontent.com/20102749/128450372-046a6eb2-a9e6-438d-82aa-6070b93a104f.png)![505](https://user-images.githubusercontent.com/20102749/128450373-5ce438ad-1fc9-40fb-9775-ae2e87eb79d7.png)

运行环境
Windows Sever 2019 Datacenter
PHP 7.4.9
Apache 2.4.46
MySQL 5.7.31

**Comment by zhichengYang-GitHub** [comment]
楼主解决了吗，我也遇到这样的问题

**Comment by zhichengYang-GitHub** [comment]
![image](https://user-images.githubusercontent.com/65290166/129153471-7d09a705-b3fa-4e41-bbac-d5e678377e58.png)
我的长这样，还有救吗？

**Comment by zhichengYang-GitHub** [comment]
而且输完这条命令后，日志文件并没有多出任何一行

**Comment by zhichengYang-GitHub** [comment]
这命令一输，日志文件也有东西了：
[laravel-2021-08-12.log](https://github.com/bs-community/blessing-skin-plugins/files/6973509/laravel-2021-08-12.log)

**Comment by zhichengYang-GitHub** [comment]
然后目的就明确了，打开fileinfo插件就行了

**Comment by zhichengYang-GitHub** [comment]
日志长这样：
[2021-08-12 15:49:54] production.ERROR: Using $this when not in object context {"exception":"[object] (Error(code: 0): Using $this when not in object context at /www/wwwroot/skin.sheepmc.top/vendor/blessing/texture-renderer/src/Blessing/Renderer/TextureUtil.php:19)
[stacktrace]
#0 /www/wwwroot/skin.sheepmc.top/plugins/texture-type-cast/src/CastTextureType.php(35): Blessing\\Renderer\\TextureUtil::isAlex()
#1 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Blessing\\TextureTypeCast\\CastTextureType->Blessing\\TextureTypeCast\\{closure}()
#2 /www/wwwroot/skin.sheepmc.top/plugins/texture-type-cast/src/CastTextureType.php(44): Illuminate\\Support\\Collection->each()
#3 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Blessing\\TextureTypeCast\\CastTextureType->handle()
#4 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
#8 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#9 /www/wwwroot/skin.sheepmc.top/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#10 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#11 /www/wwwroot/skin.sheepmc.top/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#12 /www/wwwroot/skin.sheepmc.top/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#13 /www/wwwroot/skin.sheepmc.top/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#14 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#15 /www/wwwroot/skin.sheepmc.top/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#16 /www/wwwroot/skin.sheepmc.top/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#17 {main}
"}

**Comment by zhichengYang-GitHub** [comment]
废了，我尽力了……希望官方能够接手，谢谢！

**Comment by zhichengYang-GitHub** [comment]
（可能是官方不小心在静态方法中使用$this，或者直接调用非静态的方法？）

**Comment by XieXiLin158** [comment]
日志请粘贴在paste.ubuntu.com
然后发送链接

**Comment by zhichengYang-GitHub** [comment]
> 日志请粘贴在paste.ubuntu.com
> 然后发送链接

输入完sudo php artisan texture:import 1 mcskin后并没有出现任何日志

**Comment by zhichengYang-GitHub** [comment]
> > 日志请粘贴在paste.ubuntu.com
> > 然后发送链接
> 
> 输入完sudo php artisan texture:import 1 mcskin后并没有出现任何日志

但是在输完他的前置cast的命令sudo php artisan texture:cast时
就有了日志：
https://paste.ubuntu.com/p/FdCDNkPBZK/

**Comment by zhichengYang-GitHub** [comment]
> > > 日志请粘贴在paste.ubuntu.com
> > > 然后发送链接
> > 
> > 
> > 输入完sudo php artisan texture:import 1 mcskin后并没有出现任何日志
> 
> 但是在输完他的前置cast的命令sudo php artisan texture:cast时
> 就有了日志：
> https://paste.ubuntu.com/p/FdCDNkPBZK/

![image](https://user-images.githubusercontent.com/65290166/129202723-e12a5f23-95c1-4de0-99e8-dedc8e0e6fdb.png)

**Comment by XieXiLin158** [comment]
@zhichengYang-GitHub 官方错误

**Comment by g-plane** [comment]
@zhichengYang-GitHub 「批量导入」插件依赖于「材质类型转换」插件仅仅是在代码功能上的，不需要事先执行 `php artisan texture:cast` 命令。

**Comment by g-plane** [comment]
问题已被修复，但因为该插件涉及到 Blessing Skin 本身相关模块，所以需要等到下个 Blessing Skin 版本发布才行。

**Comment by yuanzhidao** [comment]
问题修复了吗 我这边也导入不了 BlessingSkin版本是6.0.0beta3

```
[root@VM-8-4-centos skin.o0.work]# /www/server/php/74/bin/php artisan texture:import 1 storage/upload-pwqpwq/
  0/77 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
   Error 

  Using $this when not in object context

  at vendor/blessing/texture-renderer/src/Blessing/Renderer/TextureUtil.php:19
     15▕         if ($width === $image->height()) {
     16▕             $ratio = $width / 64;
     17▕             for ($x = 46 * $ratio; $x < 48 * $ratio; $x += 1) {
     18▕                 for ($y = 52 * $ratio; $y < 64 * $ratio; $y += 1) {
  ➜  19▕                     if (!$this->checkPixel($image->pickColor($x, $y))) {
     20▕                         return false;
     21▕                     }
     22▕                 }
     23▕             }

  1   plugins/batch-import/src/ImportCommand.php:64
      Blessing\Renderer\TextureUtil::isAlex()

      +1 vendor frames 
  3   plugins/batch-import/src/ImportCommand.php:82
      Illuminate\Support\Collection::each()
[root@VM-8-4-centos skin.o0.work]# 
```

**Comment by g-plane** [comment]
是修复了，只是还没发布新版本。

**Comment by yuanzhidao** [comment]
什么时候可以发布新版本呢
