### ISSUE TITLE
部分人Yggdrasil客户端链接服务器显示“登入失败:身份验证目前正在停机维护”

### ISSUE THREAD

**Issue by Aletrego** [bs-community/blessing-skin-plugins#118]
确定服务端与客户端Yggdrasil配置无问题，部分人fabric客户端更换forge后可以进入
部分时候会显示“服务端宕机”

运行环境:
PHP:7.4.2.2
System:Ubuntu 20.04 LTS
Web服务端:Apache2.4
Blessing Skin:6.0.0-Beta3
Yggdrasil API:5.1.4

**Comment by g-plane** [comment]
请提供日志。

**Comment by XieXiLin158** [comment]
草了

**Comment by wangwang-code** [comment]
PCL的启动器有时会莫名其妙的出现这种登入不了的问题

**Comment by XieXiLin158** [comment]
@wangwang-code 网络问题

**Comment by wangwang-code** [comment]
> @wangwang-code 网络问题

@XieXiLin158 
换成HMCL就行
香港tx的也能墙，那神了，还TLS加密，能被阻断那就麻了

**Comment by XieXiLin158** [comment]
> > @wangwang-code 网络问题
> 
> @XieXiLin158
> 换成HMCL就行
> 香港tx的也能墙，那神了，还TLS加密，能被阻断那就麻了

啊这
如果没有其他问题你可以直接关闭issue。

**Comment by wangwang-code** [comment]
@XieXiLin158 
你当我不想关啊，这issue不是我发起的好不好

**Comment by jonathanqwq** [comment]
这个只能使用hmcl进入
我问了pcl制作者，他表示让我反馈上
但是我懒qaq
