### ISSUE TITLE
建议出个关闭"修改角色名"功能的插件

### ISSUE THREAD

**Issue by Illusionika** [bs-community/blessing-skin-plugins#121]
我是一个离线公益服的服主，用的5.2.0皮肤站，开的单角色限制和邀请码注册，用的皮肤站来当注册入口。每次有盗版小学生的时候在游戏里ban还行不行，还要去皮肤站里修改他的邮箱和密码，不然他登上皮肤站改个角色名又是一条好汉，很麻烦

而且后台[用户管理]搜角色名经常搜不出来，要去[角色管理]去搜，然后在[用户管理]一页页翻(不支持跳转指定页数，也非常麻烦)

如果能关闭改角色名功能，那小学生就没办法再当好汉了。游戏里ban了就行，能省心不少

只关闭前台用户中心的改名就行了。后台管理中心的改名还要用的，有一些人大小写错了要帮他改下

**Comment by g-plane** [comment]
我们不会出过于限制用户功能的插件，但 BS 提供有 API，你可以自己写插件。
