### ISSUE TITLE
【建议】可否支持皮肤站与Authme单账户多角色数据对接？

### ISSUE THREAD

**Issue by TGCyrus** [bs-community/blessing-skin-plugins#122]
请见标题

**Comment by tnqzh123** [comment]
那为什么不直接使用 authlib-injector 方案呢？

**Comment by TGCyrus** [comment]
在皮肤站插件中我看见一个Authme数据对接，但是要求单角色，所以我没有安装，我不太清楚这是不是进入服务器与Authme对接后可以不用输入/login password那种很难受的命令
如果可以的话求解答

**Comment by TGCyrus** [comment]
我的意思大概是：

**Comment by TGCyrus** [comment]
我的意思大概是：

**Comment by TGCyrus** [comment]
我的意思大概是：
服务端：
装载Authme插件

客户端：
使用Authlib-injector登录：
可以跳过Authme登录插件

离线登录：
无法进入

正版登录：
需要Authme

皮肤站：
装载Yggdrasil

**Comment by tnqzh123** [comment]
GitHub 的 Issue comment 可以直接编辑，不用删除

> 在皮肤站插件中我看见一个Authme数据对接，但是要求单角色，所以我没有安装，我不太清楚这是不是进入服务器与Authme对接后可以不用输入/login password那种很难受的命令
> 
> 如果可以的话求解答

不是

**Comment by TGCyrus** [comment]
哦哦，那就没事了，感谢
