### ISSUE TITLE
传统皮肤加载方式插件未生效

### ISSUE THREAD

**Issue by LasmGratel** [bs-community/blessing-skin-plugins#124]
访问 皮肤站地址/skin/玩家名.png 返回 404

**Comment by HuangAdam** [comment]
我这也是一样，有没有具体的使用教程？

**Comment by LasmGratel** [comment]
问题仍然存在

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by HIM049** [comment]
是的，遇到了同样的问题。同时该插件也缺少必要的使用文档，根据插件源代码中设置的路由尝试请求也无法获得有效数据。
