### ISSUE TITLE
[textures-aliyun-oss] 无法在PHP8环境使用

### ISSUE THREAD

**Issue by hempflower** [bs-community/blessing-skin-plugins#132]
## 描述
当在 php8.x 环境下使用 `textures-aliyun-oss` 插件会抛出异常`RequestId:`，并且相应功能无法使用。

## 原因
`textures-aliyun-oss` 间接依赖的 `aliyuncs/oss-sdk-php` 版本较低，该版本尚未兼容PHP8.0。
详细信息可参考: https://github.com/aliyun/aliyun-oss-php-sdk/issues/154

## 排查方案
打开文件`{插件根目录}\vendor\aliyuncs\oss-sdk-php\src\OSS\OssClient.php`
找到 `const OSS_BUILD = ....` 这行，检查其值是否为 `20210825` (或更高)，如果`OSS_BUILD` 比这个值低，则受此问题影响。

## 解决方案
重新构建插件源码即可解决.

**Comment by g-plane** [comment]
它不是不支持 PHP 8 吗？只需要在我们这边重新构建就可以了吗？

**Comment by g-plane** [comment]
它不是不支持 PHP 8 吗？只需要在我们这边重新构建就可以了吗？

**Comment by hempflower** [comment]
> 它不是不支持 PHP 8 吗？只需要在我们这边重新构建就可以了吗？

最新版本已经支持PHP8，只需要重新构建下载最新的依赖就可以了。
