### ISSUE TITLE
/avatar/player/{name} 获取角色名头像的接口貌似无法工作

### ISSUE THREAD

**Issue by Stapxs** [bs-community/blessing-skin-plugins#133]
在 Doc [这儿](https://blessing.netlify.app/api/avatars-and-previews.html#%E6%A0%B9%E6%8D%AE%E8%A7%92%E8%89%B2%E5%90%8D%E8%8E%B7%E5%8F%96%E5%A4%B4%E5%83%8F) 提到了一个用于获取角色名头像的接口，在尝试使用它的时候发现貌似并不起作用。（如图）

![image](https://user-images.githubusercontent.com/42486439/151593126-839da39b-d7b5-4f69-8ab1-cca8af7f372e.png)

当前使用的 BS 版本：`"blessing_skin":"4.4.0"`

**Comment by Restent** [comment]
@Stapxs 你用的 Blessing Skin 版本似乎有点旧了，在 v5 甚至之后都是可以正常获取头像的

**Comment by Stapxs** [comment]
> @Stapxs 你用的 Blessing Skin 版本似乎有点旧了，在 v5 甚至之后都是可以正常获取头像的

好的
谢谢 ——
