### ISSUE TITLE
开启正版验证插件之后，正版用户登录时显示”用户不存在“

### ISSUE THREAD

**Issue by LIHAOCHI** [bs-community/blessing-skin-plugins#134]
PHP版本：8.0
Web服务器：Nginx
你用的什么数据库：MySQL 5.6.50
浏览器：Chrome
出现问题时浏览器地址栏上的URL：https://lhmc.club/auth/login

错误截屏：
https://raw.githubusercontent.com/LIHAOCHI/Pictures/master/Screenshot%202022-02-06%20131801.png

出现错误时皮肤站日志laravel文件的信息为：
> [2022-02-06 13:23:16] production.WARNING: Received unexpected HTTP status code from Mojang server: 403

问题具体描述：在确认开启正版验证插件之后，正版用户仍无法直接登录，且显示”用户不存在“。

**Comment by tnqzh123** [comment]
是微软正版还是 Mojang 正版？

这个功能只支持 Mojang 正版，微软正版是不支持的。如果想通过微软账户登录，可以去插件市场下载相关插件。

**Comment by LIHAOCHI** [comment]
是Mojang正版，也有这个问题
