### ISSUE TITLE
无法配置从Microsoft Live登录的插件

### ISSUE THREAD

**Issue by MasterYuan418** [bs-community/blessing-skin-plugins#139]
如图，当在登录/注册页点击“Microsoft Live登录”时：
![图片](https://user-images.githubusercontent.com/58651976/156904851-2ec3f3b4-d41b-4f66-be8c-51125f188bc4.png)
错误报告：
```
Request Id: 2ac3aa6c-873d-4a97-90a0-8ad3fdf35b00
Correlation Id: c17aaf75-2723-45c7-97f8-b9330717c301
Timestamp: 2022-03-06T01:05:04Z
Message: AADSTS900144: The request body must contain the following parameter: 'client_id'.
```

**Comment by Restent** [comment]
@MasterYuan418 它没读到你的 client_id

**Comment by MasterYuan418** [comment]
@Restent 怎么配置`client_id`字段呢？插件也没有配置界面啊

**Comment by Restent** [comment]
@MasterYuan418 你看看有没有选项是 LIVE_KEY 的？我看了一下源代码，client_id 对应的是 LIVE_KEY

**Comment by MasterYuan418** [comment]
![图片](https://user-images.githubusercontent.com/58651976/156909236-2f8a460d-7473-426b-b67e-87ad19b8e18e.png)

**Comment by mochaaP** [comment]
請將憑據於 `.env` 中配置。
<https://blessing.netlify.app/env.html#什么是-env>
