### ISSUE TITLE
[单角色限制] blessing-skin-server编译最新开发版绑定角色页面打开不正常

### ISSUE THREAD

**Issue by graytoowolf** [bs-community/blessing-skin-plugins#142]
[单角色限制]: v3.0.4
[blessing-skin-server]:157994aaea7208b3a6d651037944ec414b5b6b4e
![QQ截图20220412103544](https://user-images.githubusercontent.com/57069542/162869001-cb1b56fc-d759-4332-bd15-d47956d9ec77.png)
![QQ截图20220412104102](https://user-images.githubusercontent.com/57069542/162868998-7d75f6a1-b751-47fd-bb67-6c7645f28d0e.png)

**Comment by mochaaP** [comment]
@graytoowolf 不能 build / build 之後出不來的問題我等會看看（

**Comment by mochaaP** [comment]
https://github.com/mochaaP/blessing-skin-server/tree/hack/switch-to-elemecdn
