### ISSUE TITLE
注册页面没有邀请码输入框

### ISSUE THREAD

**Issue by CraftDream** [bs-community/blessing-skin-plugins#145]
邀请码插件启用后，注册页面没有邀请码输入框
但是点击注册会要求填写邀请码
blessingskin版本：6.0.0-rc.2
使用6.0.0-beta3时没有出现该问题 升级至最新版后出现了

**Comment by graytoowolf** [comment]
你按f12看控制台页面是不是有那个js文件没加载出来了

**Comment by CraftDream** [comment]
> 你按f12看控制台页面是不是有那个js文件没加载出来了

没有的，我是使用自己构建的 那个问题已经在dev分支修复了

**Comment by graytoowolf** [comment]
![QQ截图20220520092745](https://user-images.githubusercontent.com/57069542/169430494-3e7dca87-b1c2-4f42-af4b-57cb73314b73.png)
我这里也是这样。就是缺了JS文件

**Comment by CraftDream** [comment]
![image](https://user-images.githubusercontent.com/47418954/169449528-d3178107-b029-4ac5-99c0-f36a95d51c4b.png)

**Comment by CraftDream** [comment]
没有显示输入邀请码的输入框

**Comment by CraftDream** [comment]
重装插件也还是没有

**Comment by CraftDream** [comment]
![image](https://user-images.githubusercontent.com/47418954/169451927-76b94c0a-436f-43cb-826e-85910cc46bdb.png)

**Comment by CraftDream** [comment]
> ![QQ截图20220520092745](https://user-images.githubusercontent.com/57069542/169430494-3e7dca87-b1c2-4f42-af4b-57cb73314b73.png) 我这里也是这样。就是缺了JS文件

我们是一样的情况

**Comment by graytoowolf** [comment]
https://unpkg.com/react@17/umd/react.production.min.js
https://unpkg.com/react-dom@17/umd/react-dom.production.min.js
 
是缺了这2个JS文件。

**Comment by CraftDream** [comment]
> https://unpkg.com/react@17/umd/react.production.min.js https://unpkg.com/react-dom@17/umd/react-dom.production.min.js
> 
> 是缺了这2个JS文件。

那我应该怎么解决它

**Comment by CraftDream** [comment]
有没有解决办法？

**Comment by mochaaP** [comment]
<https://github.com/bs-community/blessing-skin-server/commit/5fc5c2c8c210386caba42885d0a3f36656736094#commitcomment-75984171>
cc @g-plane

**Comment by mochaaP** [comment]
fixed in <https://github.com/bs-community/blessing-skin-server/commit/0f3175664371d3df2d050a1b5878617d88947977>
