### ISSUE TITLE
注册邀请码插件启用并生成邀请码后注册无邀请码文本框

### ISSUE THREAD

**Issue by ilworkcn** [bs-community/blessing-skin-plugins#147]
系统 Ubuntu 20.14
使用WEB软件 Nginx1.20.2
是否使用BT  是
PHP 版本 8.1.7
Blessing Skin 程序版本 6.0.0
![QQ截图20220622212618](https://user-images.githubusercontent.com/34296329/175040567-3b689743-7a1d-48da-a0cf-58cef70aac62.png)
![QQ截图20220622212158](https://user-images.githubusercontent.com/34296329/175040581-4cfa4bcd-a628-4738-af41-e2c6249a9711.png)

**Comment by graytoowolf** [comment]
6.0.0是有这个问题.6.0.1已经修复了.

**Comment by ilworkcn** [comment]
的确是> 6.0.0是有这个问题.6.0.1已经修复了.
