### ISSUE TITLE
插件源码应如何编译？

### ISSUE THREAD

**Issue by tnqzh123** [bs-community/blessing-skin-plugins#15]
把源码拉下来之后发现根目录和插件目录里好像都没有 `composer.json` 和 `package.json` 欸...

**Comment by tnqzh123** [comment]
抱歉我眼拙了…没有 `composer.json` 的插件直接 `yarn install && yarn run install` 就可以了吗？On Jan 4, 2019 14:22, printempw <notifications@github.com> wrote:不应该吧，虽然 composer.json 是可选的，但是 package.json 是肯定有的呀？

**Comment by printempw** [comment]
看看 `package.json` 里有没有 `script.build` 字段，如果有，就 `yarn && yarn run build`；如果没有，就说明这个插件无需构建流程即可使用。
