### ISSUE TITLE
[yggdrasil-api]认证服务器宕机，请重试

### ISSUE THREAD

**Issue by FURONGsun** [bs-community/blessing-skin-plugins#158]
[环境]
CentOS7.6
apache2.4
PHP8.0
服务器为腾讯云香港轻量化服务器2c2g 30mbps
and
CentOS7.6
Nginx1.20.2
PHP8.0
前者环境为自己手动配置，后者为使用宝塔面板配置
[问题]
客户端常常会出现认证服务器宕机的情况，要多试几次才可以解决，甚至有时候试20几次就可以进去了
服务器采用mohist核心，每一次启动均需要请求ygg-api两次才可以启动成功，原因未知
一开始我认为是apache的性能占用较高导致的，因此更换了nginx，但是仍然不起效果

再多次确认的情况下，显示【认证服务器宕机】时，服务器为apache时，闲置内存为500mb 为nginx时，闲置内存为1g，(cpu占有率均不高）因此不应该是服务器性能瓶颈

**Comment by yushijinhun** [comment]
无法根据你提供的信息判断问题，建议先尝试更换皮肤站（如换 LittleSkin）、删除插件/Mod、更换服务端的方法，确定是哪部分的问题。

**Comment by FURONGsun** [comment]
经过排查，是香港服务器丢包率过高导致的，切换到国内服务器没问题了，谢谢

**Comment by FURONGsun** [comment]
我们在更换了CDN之后问题依旧出现，我们于是使用了国内一服务器对我们的域名进行ping，结果返回不存在的域名，我们意识到可能是DNS服务器的问题，于是我们将DNS服务器更改为域名注册商（腾讯云）提供的公共DNS，基本上解决了问题
