### ISSUE TITLE
forum-integration 插件启用时SQL语句出错

### ISSUE THREAD

**Issue by LamGC** [bs-community/blessing-skin-plugins#16]
启用插件时会出现SQL语句错误导致的严重错误，错误信息如下
    
    SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name "(SQL: select * from '' where 'email'= 登录邮箱 limit 1"
    
是语句缺失了表名导致的（好像WHERE条件的单引号也有问题...我不太会=w=）
没找到相关代码故提出Issue

**Comment by printempw** [comment]
https://github.com/bs-community/blessing-skin-plugins/blob/master/forum-integration/src/helpers.php#L10

打开 forum-integration 插件中的 `src/helpers.php` 文件，将第 10 行的 `localhost` 替换为 `127.0.0.1`。然后删除数据库 options 表中字段值为 `forum_db_config` 的记录，尝试重新启用插件。

**Comment by LamGC** [comment]
按照 [相同问题](https://github.com/printempw/blessing-skin-server/issues/131) 下面回复的临时解决方法解决问题了

**Comment by LamGC** [comment]
用你刚刚说的方法尝试了，还是没有解决问题，报错信息一样
