### ISSUE TITLE
[yggdrasil-api] yggdrasil 未按照预期工作

### ISSUE THREAD

**Issue by SUIBING112233** [bs-community/blessing-skin-plugins#160]
### Blessing Skin 版本

6.0.2

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Firefox

### 您正在使用的 Web Server

Nginx

### 您正在使用宝塔吗？

- [ ] 是

#### 启动器方面

在正确加载Yggdrasil地址并且正确输入用户名时提示`无法连接认证服务器，可能是网络问题。`
但是使用错误的用户却正常提示`用户xx不存在`

#### BlessingSkin与Yggdrasil插件方面

日志文件中已经成功记录错误，见下文

#### 额外描述

不仅仅是管理员用户，普通新注册的用户也产生该问题.

使用CloudFlare，并且已经根据文档中进行配置。在CloudFlare开发模式中依然产生该问题。

### 错误日志

一共产生三份日志

- [yggdrasil.log](https://paste.ubuntu.com/p/tpgTR6ZR6h/)
- [laravel.log](https://paste.ubuntu.com/p/Dqd6584mNh/)
- [HMCL's log](https://paste.ubuntu.com/p/Dz28tkPqkR/)

### 重现步骤

- 正确配置皮肤站，确认可以正常登录。
- 安装Yggdrasil插件，并且按要求配置皮肤站与HMCL。
- 产生异常。

若需要测试，则测试账号为如下
- 皮肤站地址: [OakMemory Skin](https://skin.krysztal.dev)
- 用户邮件: test123@example.com
- 用户名: test123
- 密码: 11223344

**Comment by SUIBING112233** [comment]
> @SUIBING112233 所有軟體的版本？

Yggdrasil插件为8月14日从插件市场安装，版本为`v5.1.5`。
Nginx为`1.22.0`。
HMCL为`3.5.5`。
PHP为`8.1.9`。
系统环境为`Debian Bullseye`，但是整个皮肤站运行在Docker之中，测试迁移出Docker于实体环境依然无效。

已安装插件为如下
- 注册邀请码 `v3.1.2`
- 代理信任 `v0.1.3`
- 单角色限制 `v3.0.0`（未启用）
- YggdrasilAPI `5.1.5`

**Comment by mochaaP** [comment]
@SUIBING112233 伺服器的 authlib-injector 版本？

**Comment by SUIBING112233** [comment]
> @SUIBING112233 伺服器的 authlib-injector 版本？

未使用服务器端authlib-injector，客户端authlib-injector为HMCL最新版本，未知authlib-injector版本

**Comment by SUIBING112233** [comment]
收到，将会在稍晚尝试。

**Comment by SUIBING112233** [comment]
在添加后再次登录依然失败，产生的日志如下
- [yggdrasil.log](https://paste.ubuntu.com/p/tQ6FY2P7y8/)
- [laravel.log](https://paste.ubuntu.com/p/5p85ggF9F7/)

**Comment by mochaaP** [comment]
@SUIBING112233 禁用並重新啟用 yggdrasil-api
沒有反應的話檢查 plugins/yggdrasil-api/callbacks.php 是否正常

**Comment by SUIBING112233** [comment]
感谢您的耐心回复与解答，YggdrasilAPI已经正常工作。

**Comment by binggo999** [comment]
> 感谢您的耐心回复与解答，YggdrasilAPI已经正常工作。
> 
> 测试账号已经关闭。

请问你是如何解决的？
