### ISSUE TITLE
mojang-verification无法使用

### ISSUE THREAD

**Issue by Hacker-yfs** [bs-community/blessing-skin-plugins#167]
在进行正版验证时提示invalid_request: The provided request must include a 'client_id' input parameter.
查看插件的bootstrap.php发现调用env的Microsoft应用的变量为MICROSOFT_KEY、MICROSOFT_SECRET、MICROSOFT_REDIRECT_URI
![屏幕截图 2022-11-19 002008](https://user-images.githubusercontent.com/86495643/202752003-c364b18c-db1f-44bc-b8ef-f8d9dac91953.png)
而在.env文件内使用的Microsoft登陆配置为LIVE_KEY、LIVE_SECRET、LIVE_REDIRECT_URI
![屏幕截图 2022-11-19 002157](https://user-images.githubusercontent.com/86495643/202752352-5ddce5a0-a057-421f-9dbb-3ca10ce14960.png)
当我将bootstrap.php内MICROSOFT_KEY、MICROSOFT_SECRET、MICROSOFT_REDIRECT_URI改为LIVE_KEY、LIVE_SECRET、LIVE_REDIRECT_URI发现不会再报错，但却出现正版验证无法通过的情况（点击验证后直接返回用户首页而没有通过验证，已确定所登陆的Microsoft拥有Minecraft）

请问这是bug吗？

**Comment by Simba98** [comment]
不是，见：https://github.com/bs-community/blessing-skin-plugins/tree/master/plugins/mojang-verification

**Comment by Hacker-yfs** [comment]
感谢
