### ISSUE TITLE
请支持Flarum论坛

### ISSUE THREAD

**Issue by Ghost-chu** [bs-community/blessing-skin-plugins#17]
建议增加对[Flarum](https://flarum.org//)论坛程序进行数据对接，让玩家使用这个论坛系统账号密码登录皮肤站，使用MIT公共协议，数据库+论坛结构简单。

**Comment by ExDragine** [comment]
建议增加对XenForo论坛程序以及建议增加对MediaWiki的数据对接

**Comment by tnqzh123** [comment]
@ExDragine MediaWiki 你是认真的吗…On Feb 10, 2019 14:19, ExDragine <notifications@github.com> wrote:建议增加对XenForo论坛程序以及建议增加对MediaWiki的数据对接

**Comment by tnqzh123** [comment]
@ExDragine MediaWiki 你是认真的吗…

**Comment by ExDragine** [comment]
> @ExDragine MediaWiki 你是认真的吗…

算是开玩笑？开玩笑的
