### ISSUE TITLE
config-generator配置生成插件页面加载缓慢

### ISSUE THREAD

**Issue by 615303619** [bs-community/blessing-skin-plugins#188]
近几天加载特别缓慢不知道是什么问题

**Comment by SRY-CTB** [comment]
jsdelivr在抽风（恼火
我的建议：在skin.com/plugins/config-generator/views目录下，修改generator.twig文件中的atom-one-light.min.css文件加载地址，不介意可使用我的//assets.shanrenyi.top/css/plugins/atom-one-light.min.css

**Comment by 615303619** [comment]
> jsdelivr在抽风（恼火 我的建议：在 skin.com/plugins/config-generator/views 目录下，修改generator.twig文件中的atom-one-light.min.css文件加载地址，不介意可使用我的//assets.shanrenyi.top/css/plugins/atom-one-light.min.css

我也发现是这个问题了，不过今天好像恢复正常了
