### ISSUE TITLE
插件适配 v4 进度跟踪

### ISSUE THREAD

**Issue by g-plane** [bs-community/blessing-skin-plugins#19]
- [x] authme-integration
- [x] avatar-api（已整合进核心）
- [x] batch-import
- [x] bs-super-cache（已整合进核心）
- [x] config-generator
- [x] example-plugin
- [x] forum-integration
- [x] get-score-by-sharing（已整合进核心）
- [x] hello-dolly
- [x] insane-profile-cache
- [x] invitation-codes
- [x] redis（已整合进核心）
- [x] report-texture（已整合进核心）
- [x] seo-meta-tags（已整合进核心）
- [x] single-player-limit（已整合进核心）
- [x] static-file-cdn（已整合进核心）
- [x] textures-aliyun-oss
- [x] textures-qcloud-cos
- [x] textures-qiniu-storage
- [x] yggdrasil-api

**Comment by tnqzh123** [comment]
之前的 `next` 分支中的插件不能直接使用吗？

**Comment by g-plane** [comment]
next 分支已重命名为现在的 master 分支。

**Comment by tnqzh123** [comment]
> next 分支已重命名为现在的 master 分支。

之前 `next` 分支（即现在的 `master` 分支）中的插件不能直接在 v4 上使用吗？

**Comment by g-plane** [comment]
有些可以，有些不能。

**Comment by tnqzh123** [comment]
话说插件要不要也 relicense 到 MIT？现在还是 GPLv3 吧

**Comment by g-plane** [comment]
@printempw @dz-paji 意见？

**Comment by printempw** [comment]
我没意见

**Comment by dz-paji** [comment]
我也没意见。

**Comment by g-plane** [comment]
We reached it!
