### ISSUE TITLE
无法打开插件市场

### ISSUE THREAD

**Issue by Jinomee** [bs-community/blessing-skin-plugins#192]
blessing skin 6.0.2
php 8.0
nginx 1.21.4
mysql 5.7.40
![image](https://github.com/bs-community/blessing-skin-plugins/assets/117045178/7c435c81-99da-4923-b370-bf5cb8a0afb9)
尝试打开插件市场就会报错

**Comment by Yue-plus** [comment]
这是一个已知问题：[插件市场无法打开 / Unable to load plugin market / Undefined array key "packages" · Issue #454 · bs-community/blessing-skin-server](https://github.com/bs-community/blessing-skin-server/issues/454)

临时解决方案：在 [bs-community/plugins-dist](https://github.com/bs-community/plugins-dist) 下载所需所需插件，并通过 *插件管理* 页面上传 `.zip` 文件安装。

**Comment by Yue-plus** [comment]
顺便说下，如果你要装 Yggdrasil API 的话请 `v5.1.1` 高版本的实测用不了。
