### ISSUE TITLE
authme-integration插件同步问题

### ISSUE THREAD

**Issue by binggo999** [bs-community/blessing-skin-plugins#197]
authme-integration插件2.4.3玩家在游戏内注册之后无法自动同步到皮肤站登录，user表不会自动同步到player。
2.4.0插件会自动同步但是有时会重复同步多次。并且玩家数量多之后每次打开网站都会检查一次，导致网站出现504.

另外有没有临时解决该问题的方法？

**Comment by binggo999** [comment]
我理解插件的作用了，这不是bug。请关闭该issues。

**Comment by tnqzh123** [comment]
为什么不尝试切换到 authlib-injector 外置登录方案呢？

**Comment by binggo999** [comment]
> 为什么不尝试切换到 authlib-injector 外置登录方案呢？

服务器为基岩互通直连服，使用外置登录不太方便，玩家有些也不熟悉外置登录方案
