### ISSUE TITLE
yggdrasil在启动器启动时“无法链接认证服务器”

### ISSUE THREAD

**Issue by WillowKoishi** [bs-community/blessing-skin-plugins#203]
Blessing Skin 版本
6.0.2

PHP 版本
8.0.16

出现问题时所使用的浏览器
edge\chrome

您正在使用的 Web Server
Nginx

您正在使用宝塔吗？
 是
出现了什么问题？

同issue 160：https://github.com/bs-community/blessing-skin-plugins/issues/160
但按照该issue内所有解决方案操作后依然无法工作
JWT_SECRET有内容且正常
https://skin.fairingstudio.com/api/yggdrasil可访问，内容正常

启动器方面
在正确加载Yggdrasil地址并且正确输入用户名时提示无法连接认证服务器，可能是网络问题。
但是使用错误的用户却正常提示用户xx不存在

额外描述
不仅仅是管理员用户，普通新注册的用户也产生该问题.

不使用CloudFlare

log文件：https://fairingstudio.com/log/laravel.log
https://fairingstudio.com/log/hmcl.log

**Comment by tnqzh123** [comment]
Issue closed due to inactivity.
