### ISSUE TITLE
正版验证插件验证后还是显示没有验证

### ISSUE THREAD

**Issue by kldhsh123** [bs-community/blessing-skin-plugins#205]
正版验证插件验证后还是显示没有验证但是一验证没有确定界面直接回调
![image](https://github.com/bs-community/blessing-skin-plugins/assets/123392781/9b21caae-6401-45f1-99fd-11a74328bb4f)

**Comment by kldhsh123** [comment]
我将MICROSOFT_REDIRECT_URI换成了示例的[https://这是网站.top/mojang/callback出现了](https://xn--0ivx37bbidvvv.top/mojang/callback%E5%87%BA%E7%8E%B0%E4%BA%86)
500 Internal Server Error
详细信息：Undefined array key "access_token"

**Comment by pan90** [comment]
同

**Comment by PonderFox0643** [comment]
https://help.minecraft.net/hc/en-us/articles/16254801392141
去这里点击那个申请表格并填写它，审核通过后就可以正版验证了
