### ISSUE TITLE
论坛数据对接插件出错

### ISSUE THREAD

**Issue by EterLzb** [bs-community/blessing-skin-plugins#21]
之前有人提过这个。。。
是我的问题还是什么。。。
php : 7.2.16
nginx : 1.16.0
mysql : 5.6.43
500 Internal Server Error 
详细信息：SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where `email` = ? limit 1' at line 1 (SQL: select * where `email` = **内容被隐藏** limit 1)

**Comment by g-plane** [comment]
这个问题已在今早修复。
