### ISSUE TITLE
forum-integration 可能会导致论坛上用户名为 null

### ISSUE THREAD

**Issue by Asnxthaony** [bs-community/blessing-skin-plugins#27]
用户在皮肤站注册账号后，在用户名处填写邮箱，并登录论坛账号，会使用户名变为null

![1](https://user-images.githubusercontent.com/12845643/58089420-44a03780-7bf7-11e9-9c08-add14fc6aa44.png)
![2](https://user-images.githubusercontent.com/12845643/58089318-086cd700-7bf7-11e9-8409-1da08559d602.png)

**Comment by g-plane** [comment]
为什么要在“用户名”那里填写邮箱？邮箱是邮箱，不是用户名。

**Comment by Asnxthaony** [comment]
> 为什么要在“用户名”那里填写邮箱？邮箱是邮箱，不是用户名。

discuz默认会选择用户名，许多用户不会在意这一点。。。

**Comment by g-plane** [comment]
这不能怪我吧？

**Comment by g-plane** [comment]
先关闭着了……目前我不觉得是插件的问题。
