### ISSUE TITLE
forum-intergration 无法对接论坛

### ISSUE THREAD

**Issue by aoxiangtianji** [bs-community/blessing-skin-plugins#28]
我使用oneinstack的lamp，php 7.3.5， apache 2.4， 使用论坛对接插件对接flarum，报错提示
Array to string conversion (View: _/data/wwwroot/skin.axtjblog.cc/plugins/forum-integration/views/config.blade.php)[https://skin.axtjblog.cc/laravel.log](url)，并且会导致后面无法登录

**Comment by g-plane** [comment]
这个 log 的链接打不开。

**Comment by aoxiangtianji** [comment]
> 这个日志的链接打不开。

抱歉，应该是这个：[这里](https://skin.axtjblog.cc/laravel.log)

**Comment by g-plane** [comment]
这个 issue 被 close 了？那问题解决了吗？

**Comment by aoxiangtianji** [comment]
我也不知道为啥就关了，问题没解决

**Comment by g-plane** [comment]
是刚刚打开配置页面就这样还是在填写好数据库信息并点击「提交」按钮后才出现这个错误？

**Comment by aoxiangtianji** [comment]
提交后。

**Comment by g-plane** [comment]
你的插件版本和 BS 版本是多少？

**Comment by aoxiangtianji** [comment]
我可以确定，全部最新的。

**Comment by g-plane** [comment]
就不能说个具体版本吗？之前有人也说是最新的，结果一问是旧的。

**Comment by aoxiangtianji** [comment]
插件版本2.1.0
论坛版本4.2.0

**Comment by g-plane** [comment]
你试试在 [这一行](https://github.com/bs-community/blessing-skin-plugins/blob/8fe45edbfe7414b35df53a83052542f3f9b4f480/forum-integration/views/config.blade.php#L24) 的下面加一句：

```php
dd($config);
```

**Comment by aoxiangtianji** [comment]
是在if里面么？

**Comment by g-plane** [comment]
是。

**Comment by aoxiangtianji** [comment]
不行，仍然报错

Array to string conversion (View: /data/wwwroot/skin.axtjblog.cc/plugins/forum-integration/views/config.blade.php)
--

**Comment by g-plane** [comment]
你试一试用注释的方法来确定是哪里出问题，毕竟日志上也没写是哪一行出问题。

**Comment by aoxiangtianji** [comment]
我开了.env中的debug模式，或许可以，你看看？
[图片](https://axtjblog.cc/debug.png)

**Comment by g-plane** [comment]
这里的内容跟日志是一样的。

**Comment by aoxiangtianji** [comment]
ok

**Comment by tnqzh123** [comment]
我瞎说一下(

@aoxiangtianji 你试试把 `view/config.blade.php` 的第 25 行注释掉再提交，看看会不会报错？

这一行代码的作用应该是保存设置，所以注释掉之后不会保存设置是正常情况。

**Comment by aoxiangtianji** [comment]
不成功。和上面的报错一毛一样

> 我瞎说一下(
> 
> @aoxiangtianji 你试试把 `view/config.blade.php` 的第 25 行注释掉再提交，看看会不会报错？
> 
> 这一行代码的作用应该是保存设置，所以注释掉之后不会保存设置是正常情况。

**Comment by aoxiangtianji** [comment]
我也不会PHP，帮不上忙啊
OTATO

**Comment by g-plane** [comment]
你试一试用注释的方法来确定是哪里出问题。将 `config.blade.php` 文件中 `always` 方法中的函数，逐个部分进行注释，以便帮助我们定位问题。

**Comment by aoxiangtianji** [comment]
我要不给你ssh你来吧我真不会啊( ≧Д≦)

Pig Fang <notifications@github.com> 于 2019年6月3日星期一 20:40写道：

**Comment by g-plane** [comment]
我没空提供这样的一对一服务。

**Comment by aoxiangtianji** [comment]
抱歉。我试试
