### ISSUE TITLE
更新插件后，出现500错误

### ISSUE THREAD

**Issue by AndyChuck** [bs-community/blessing-skin-plugins#31]
刚才更新了batch-import和hitokoto，由于是一起更新的，不确定是哪个出了问题，刷新页面后，站点出现500错误
![err](https://user-images.githubusercontent.com/23419265/60442872-8daec700-9c4c-11e9-84f8-ae994679b743.png)

**Comment by tnqzh123** [comment]
我觉得可能是 `hitokoto` 的问题🤔

你试一下把 `plugins/hitokoto/bootstrap.php` 的第 9 行末尾的逗号删掉看一下？

**Comment by g-plane** [comment]
是 PHP 7.1 或 PHP 7.2 吗？

**Comment by AndyChuck** [comment]
> 是 PHP 7.1 或 PHP 7.2 吗？

7.2

**Comment by AndyChuck** [comment]
> 我觉得可能是 `hitokoto` 的问题 
> 
> 你试一下把 `plugins/hitokoto/bootstrap.php` 的第 9 行末尾的逗号删掉看一下？

好像并没有什么用

**Comment by tnqzh123** [comment]
@AndyChuck

> 好像并没有什么用

在 LittleSkin 上这样做就修好了的样子 🤔

不过我把第 8 行到第 10 行写在一行里了

**Comment by tnqzh123** [comment]
@AndyChuck 稍后将发布新版本 `hitokoto`，请注意更新。

如果无法访问皮肤站管理页面，删掉 `plugins/hitokoto/` 即可。
