### ISSUE TITLE
新插件请求：材质标签

### ISSUE THREAD

**Issue by alexskim** [bs-community/blessing-skin-plugins#38]
增加材质标签插件，理想情况下的具体具体细节如下：

- 用户在上传材质时上传材质后可以设置（添加或删除）任意材质标签
- 一个材质可以设置不同的标签
- 用户可以根据材质标签查找材质
- 皮肤库首页增设「标签」一栏，随机抽取一些皮肤库中的材质的标签展示给用户，当用户点击某个标签时可以直接搜索这个标签的材质
- 在衣柜中也展示材质标签（显示在皮肤预览下方就好）并提供标签搜索

Demo 可以参考 WordPress 的「标签」功能。

上述功能不一定要全部实现，但最好在可行的情况下实现尽量多的功能。

_Edit by @tnqzh123_

**Comment by g-plane** [comment]
这是皮肤库中的标签功能而不是衣柜中的标签功能？

**Comment by tnqzh123** [comment]
@g-plane 

> 这是皮肤库中的标签功能而不是衣柜中的标签功能？

用户也只有在上传材质时和皮肤库材质详情页面能设置材质标签了吧？我觉得衣柜页面并不方便用户操作。

**Comment by g-plane** [comment]
但也许不同的人会有不同的分类方法，而皮肤库的信息是全站统一的。

**Comment by tnqzh123** [comment]
@g-plane 

> 但也许不同的人会有不同的分类方法，而皮肤库的信息是全站统一的。

> - 一个材质可以设置不同的标签

**Comment by g-plane** [comment]
「标签」不等同于分类，这意味着一个材质肯定是可以有多个标签的。但每个人对于不同的标签理解不同，对于同一个材质，有人喜欢应用「标签 A」，有人喜欢应用「标签 B」（同时他不希望有「标签 A」），这就存在冲突。

**Comment by tnqzh123** [comment]
@g-plane 

> 但也许不同的人会有不同的分类方法，而皮肤库的信息是全站统一的。

我觉得应该只允许上传者设置标签，以防止有些不怀好意的用户捣乱。

> 「标签」不等同于分类，这意味着一个材质肯定是可以有多个标签的。但每个人对于不同的标签理解不同，对于同一个材质，有人喜欢应用「标签 A」，有人喜欢应用「标签 B」（同时他不希望有「标签 A」），这就存在冲突。

可以实现「排除」功能，在搜索带有标签 A 的材质时排除带有标签 B 的材质。

当然也可以针对衣柜再单独做一个标签功能…但是会很累吧

**Comment by g-plane** [comment]
这样反而没意义，标签功能本来就是方便自己的，而不是方便他人的。

**Comment by g-plane** [comment]
手误了。

**Comment by tnqzh123** [comment]
@g-plane 

> 这样反而没意义，标签功能本来就是方便自己的，而不是方便他人的。

那大概是我理解错了…

我再想想针对衣柜的方案，稍后会再开一个 Issue。（可能要集成进核心，因为当前 `user_closet` 表中没有用于存储标签的字段，插件要再开数据表的话我觉得会很麻烦，所以 Issue 可能会开在 [bs-community/blessing-skin-server](https://github.com/bs-community/blessing-skin-server)，不过具体工作量我其实不太清楚…）

PS：同时在皮肤库中实现「材质标签」我觉得也是可以考虑一下的，这样可以方便用户在皮肤库中查找到自己心仪的材质。

**Comment by g-plane** [comment]
创建数据表不难，难在改前端。
