### ISSUE TITLE
能不能添加新用户人工审核功能

### ISSUE THREAD

**Issue by pentyum** [bs-community/blessing-skin-plugins#40]
你好，我的服务器需要人工审核新用户，能不能弄一个这样的插件或者功能？谢谢！

**Comment by KYLN24** [comment]
可以使用邀请码插件，审核了的人给邀请码才能注册。

**Comment by g-plane** [comment]
确实，可以使用邀请码插件。如果是单纯地避免无关用户来注册，这个插件够用了。

目前先关闭此 issue 了，如果需要其它讨论，可继续。
