### ISSUE TITLE
插件安装启用后报错无法使用

### ISSUE THREAD

**Issue by 67141988** [bs-community/blessing-skin-plugins#43]
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: select * from `` where `email` = admin@sey.ink limit 1)

**Comment by 67141988** [comment]
forum-integration

**Comment by Asnxthaony** [comment]
请在「论坛数据对接」插件的配置页面正确填写以下项目：
- 论坛程序的用户数据表名称（请根据你的实际情况填写）。

**Comment by 67141988** [comment]
无法打开插件配置页面

**Comment by 67141988** [comment]
安装启用后 整站都是 这个错误

**Comment by tnqzh123** [comment]
请在插件配置页面正确填写目标数据库连接信息后重试。如果无法打开插件配置页面，请直接修改 options 数据表中的对应记录。

已知「论坛数据对接」插件存在致命问题，但其维护工作已被无限期搁置（因为没有找到解决方案）。能不能使用全随缘。

还有，请善用 GitHub Issues 的编辑功能，频繁回复 Issue 会造成邮箱轰炸。
