### ISSUE TITLE
正版验证与yggdrasil问题、邀请码插件新功能建议、新插件建议

### ISSUE THREAD

**Issue by KYLN24** [bs-community/blessing-skin-plugins#46]
（纯用户视角，自己不会写，有能写的朋友考虑一下😂感谢）
### 新增插件
1. 一个简易的在线皮肤披风编辑器
2. 超过一定时间未登录（皮肤站或yggdrasil均为登录过）回收账号（或取消激活状态（“激活状态”见下文的建议））

#### 邀请码插件
1. 正版账号也需要邀请码（使用邀请码实现一个类似白名单的功能）
2. 可以先注册账号再使用邀请码激活（便于实现基于邀请码的入服测试）
#### 正版验证与yggdrasil
[yggdrasil-api 插件的 wiki](https://github.com/bs-community/yggdrasil-api/wiki/0x03-配合-authlib-injector-使用#%EF%B8%8F-配置启动器) 中表示

> 如果您或您所使用的皮肤站安装有「正版验证」插件，并且您的账号经过了正版验证，则可以使用 任意一款启动器（只需要允许自定义 JVM 参数），然后在启动器的设置中修改 JVM 参数以使游戏客户端加载 authlib-injector 即可。

使用 HMCL 的外置登录能正常地登入服务器。然而，正版启动器（最新版 authlib-injector.jar 已放到正确位置）中添加启动参数（```-javaagent:authlib-injector.jar=我的皮肤站地址/api/yggdrasil```），无法正常登入服务器。有趣的是，在 HMCL 中使用正版登录，然后添加上述启动参数依然无法登入服务器。不知是插件的问题还是启动参数未正确填写的问题。如果是启动参数未正确填写的问题，请问应该如何填写呢（wiki上并未就此展开介绍）？

如果可以的话，希望能在wiki上写得更清楚一点。

你们的皮肤站真的很好用！麻烦开发者了！谢谢！

**Comment by g-plane** [comment]
皮肤站不是在线皮肤编辑器，即使是披风，这样功能是不会去实现的——这是在很久之前就有人讨论过的问题。

**Comment by tnqzh123** [comment]
@KYLN24 

## 新增插件
> 简易的在线皮肤披风编辑器

v3 有过这个插件（`skin-utilities`），但自 v4 起这个插件就不再维护了。我个人认为，编辑材质还是使用专业的工具来做会比较好，直接在网页上做反倒容易弄巧成拙。

> 超过一定时间未登录就回收账号

这点是不现实的。要知道，大部分用户更换材质的频率都是很低的，基本上设置完角色的材质就不会再登录皮肤站了。

## 正版验证于 Yggdrasil API 的问题
请确认你在皮肤站中的角色的 UUID 与正版账号的角色的 UUID 相同。你可以在个人资料页面同步 UUID。

**Comment by KYLN24** [comment]
好的，谢谢回复。

**Comment by KYLN24** [comment]
谢谢回复，正在尝试。

**Comment by KYLN24** [comment]
可以了，谢谢回复。
