### ISSUE TITLE
single-player-limit无效

### ISSUE THREAD

**Issue by GiriNeko** [bs-community/blessing-skin-plugins#50]
我的皮肤站版本是4.4.0
为了方便管理，我需要这个插件
但启用后，皮肤站仍然可以创建多个角色，启动器也可以选择多个角色。
![image](https://user-images.githubusercontent.com/21117880/77548833-0dbb4200-6eea-11ea-9b2a-d9e820782806.png)
![image](https://user-images.githubusercontent.com/21117880/77548779-faa87200-6ee9-11ea-8cbb-a56f41470f76.png)
![image](https://user-images.githubusercontent.com/21117880/77548918-262b5c80-6eea-11ea-9dfa-6a989fd1c702.png)
注：该角色是我开启插件之后创建的。

**Comment by tnqzh123** [comment]
没有管理员权限的普通用户可以创建多个角色吗？

Yggdrasil API 插件按理来说不需要进行特殊调整，具体原因可以研究一下 Yggdrasil API 相关的技术规范。

**Comment by GiriNeko** [comment]
非管理员用户也可以。
我服想实行一人一号的规定，不希望一个账户下能创建多个小号。



发自我的小米手机
在 Steven Qiu <notifications@github.com>，2020年3月25日 下午10:50写道：

没有管理员权限的普通用户可以创建多个角色吗？

Yggdrasil API 插件按理来说不需要进行特殊调整，具体原因可以研究一下 Yggdrasil API 相关的技术规范。

**Comment by Asnxthaony** [comment]
请问 `options` 表中中的 `single_player` 的值是否为 `1`

**Comment by GiriNeko** [comment]
我并没有找到这个表，然后刚刚手动新建了一个，问题解决。
谢谢你

**Comment by tnqzh123** [comment]
@GiriNeko 不可能没有 options 表的吧…

**Comment by GiriNeko** [comment]
额...我指的是并没有找到single_player
