### ISSUE TITLE
mounted的时间似乎有问题

### ISSUE THREAD

**Issue by mcoo** [bs-community/blessing-skin-plugins#52]
刚刚更新的注册邀请码插件3.0.0中无法在注册页面中插入相关表格
![QQ图片20200408164844](https://user-images.githubusercontent.com/26184088/78764281-e8820580-79b8-11ea-999a-c9af8d0dc4cf.png)
```js
blessing.event.on('mounted', ({ el }) => {
	$("main").before('<div class="input-group mb-3"><input class="form-control" id="invitation-code" required="required" type="text" placeholder="邀请码"> <div class="input-group-append"><div class="input-group-text"><span class="fas fa-id-card"></span></div></div></div>');
})
```
这样修改后可以显示出相关表格，但有点强迫症 input在form外边了，应该是mounted事件的时间有问题，在之前就触发了这个事件

**Comment by mcoo** [comment]
虽然这样也可以使用就是了

**Comment by g-plane** [comment]
什么表格……？

**Comment by mcoo** [comment]
<input class="form-control" id="invitation-code" required="required" type="text" placeholder="邀请码">这个东西在新版本无法显示出来

**Comment by mcoo** [comment]
`<input class="form-control" id="invitation-code" required="required" type="text" placeholder="邀请码"> `

**Comment by g-plane** [comment]
我这边适配的时候是测试过的，当时没问题。我等下再测试一下。

**Comment by mcoo** [comment]
ok 你测试测试

**Comment by Asnxthaony** [comment]
我这边测试了一下。
邀请码框可以在 Firefox 浏览器中正常渲染，在 Chrome 浏览器中不会被渲染。

可能会对此问题有帮助的链接：
https://cn.vuejs.org/v2/guide/reactivity.html#%E5%BC%82%E6%AD%A5%E6%9B%B4%E6%96%B0%E9%98%9F%E5%88%97

**Comment by g-plane** [comment]
确认存在这个问题。

**Comment by g-plane** [comment]
已尝试修复。
