### ISSUE TITLE
有没有可能添加个uuid 获取皮肤的接口了 

### ISSUE THREAD

**Issue by graytoowolf** [bs-community/blessing-skin-plugins#55]
https://crafatar.com/skins/4d19c01f518c3977ac1cdba4d0f77e51.png

就像这种接口

**Comment by tnqzh123** [comment]
@g-plane 

> 安装 Yggdrasil API 插件就是了。

Yggdrasil API 本身并没有提供这种 API…有也是第三方验证服务器自行实现的扩展，但是 BS 的 `yggdrasil-api` 是没有实现的。

@graytoowolf 建议自行编写相关插件。

**Comment by g-plane** [comment]
不是可以先通过 UUID 查到角色，再通过角色查到材质吗？

**Comment by tnqzh123** [comment]
@g-plane 

> 不是可以先通过 UUID 查到角色，再通过角色查到材质吗？

他需要的是，直接通过 UUID 查询到材质。

在 Mojang 官方的 Yggdrasil API 中，UUID 只能查询到角色 Profile，客户端需要解析 Profile 中的 Properties 去获取材质的 URL，然后再去请求材质，并根据 Properties 中的 Metadata 判定材质模型。

**Comment by g-plane** [comment]
材质与 UUID 之间不管在逻辑上还是物理上本来就不存在关联。

**Comment by graytoowolf** [comment]
> 材质与UUID之间无论在逻辑上还是物理上本来就不存在关联。

我用你编写的 角色名 获取皮肤 那个插件改了下    我先获取uuid对应的角色 在用角色去获取皮肤     你在回复中提到yggd 我还以为有这种接口
