### ISSUE TITLE
配置生成(config-generator) 生成的接口 与实际 接口不一致 

### ISSUE THREAD

**Issue by graytoowolf** [bs-community/blessing-skin-plugins#59]
实际接口: http://您的皮肤站地址/textures/那一串字符串

配置生成接口:http://您的皮肤站地址/csl/textures/那一串字符串

会导致皮肤MOD 获取不到皮肤

**Comment by g-plane** [comment]
有图吗？

**Comment by graytoowolf** [comment]
![1](https://user-images.githubusercontent.com/57069542/84649003-607c2700-af38-11ea-81ba-946633643ad4.png)
![2](https://user-images.githubusercontent.com/57069542/84649006-6114bd80-af38-11ea-8b1a-169615a0cac8.png)

**Comment by g-plane** [comment]
既然你报告「配置生成」插件，那就要发插件的图啊……

**Comment by graytoowolf** [comment]
![3](https://user-images.githubusercontent.com/57069542/84650336-9cb08700-af3a-11ea-8ef1-7fe78b4a8024.png)
![4](https://user-images.githubusercontent.com/57069542/84650338-9d491d80-af3a-11ea-958f-e51d054bc902.png)
具体网站我涂掉了  免得有打广告的嫌疑

**Comment by graytoowolf** [comment]
![5](https://user-images.githubusercontent.com/57069542/84650415-c4075400-af3a-11ea-8ea0-39b5863c094e.png)

**Comment by g-plane** [comment]
其实这是 BS 的 bug，并不是插件的问题。

**Comment by graytoowolf** [comment]
是这样吗 可是你帮助文档里也不带 csl 的 
网址不带csl 就可以的 .
 我也不知道是那个的问题 ,你说是BS 的bug 那就是.
我还以为是这个插件多了点东西了.

**Comment by g-plane** [comment]
一般都不带的呀……因为很少人用 USM，所以 CSL 是默认的。

**Comment by graytoowolf** [comment]
嗯嗯  . 
你看着修下吧 .
生成的配置文件 里面的地址 去掉CSL  是不是就完美了. 现在 地址 带CSL  usm 的地址 已经没用了 .

**Comment by tnqzh123** [comment]
@graytoowolf 

> 生成的配置文件 里面的地址 去掉CSL  是不是就完美了. 现在 地址 带CSL  usm 的地址 已经没用了 .

“`/usm/` 没用”是因为你没有安装对应的插件。

因为 USM 和传统加载的用户较少，这两个 API 被抽出来，做成了插件。核心默认只支持 CSL API。
