### ISSUE TITLE
[正版验证][功能请求]用户管理界面显示是否正版

### ISSUE THREAD

**Issue by Alice-space** [bs-community/blessing-skin-plugins#61]
希望可以在用户管理界面显示一个用户是否是正版

**Comment by Alice-space** [comment]
辛苦作者，已打赏

**Comment by g-plane** [comment]
感谢。
不过，由于用户管理页面还没有为插件提供接口和钩子，因此实现起来可能会相对麻烦些。

**Comment by g-plane** [comment]
这个功能可能需要推迟到 v5 正式版发布以后才考虑设计并实现。
另外，能说说具体的需求吗？说不定有更好的方案。

**Comment by g-plane** [comment]
目前没有实现该功能的计划。
