### ISSUE TITLE
[Yggdrasil] User not found when user exists

### ISSUE THREAD

**Issue by Aeris1One** [bs-community/blessing-skin-plugins#71]
Hi,
I'm using a modified version of Helios launcher to use Yggdrasil API on my Blessing Skin instance.
The launcher asks me for login before letting me launch Minecraft (so I cannot use Authlib-injector).
I replaced all occurences of authserver.mojang.com to my server Yggdrasil address and replaced endpoints`/authenticate`, `/invalidate`,... by `/authserver/authenticate`, `/authserver/invalidate`,...

When I log in with a username it says that the user does not exists and when I log in with my email (with 3 players added) it says I don't have a Premium account cause the server response fires a code (screenshot below in comments)

Can you help me debugging this ?

The script which manage connection to Yggdrasil : 
https://github.com/Terebros-MC/HeliosLauncher/blob/master/app/assets/js/mojang.js

**Comment by Aeris1One** [comment]
![image](https://user-images.githubusercontent.com/29739547/88093986-16b7d980-cb93-11ea-84a9-2f22a0f16099.png)

**Comment by Aeris1One** [comment]
When I login with email it says that I've not purchased Minecraft cause of this code : 
![image](https://user-images.githubusercontent.com/29739547/88094646-34397300-cb94-11ea-8a0e-ffa03f1149ff.png)

**Comment by Asnxthaony** [comment]
> When I login with email it says that I've not purchased Minecraft cause of this code :
> ![image](https://user-images.githubusercontent.com/29739547/88094646-34397300-cb94-11ea-8a0e-ffa03f1149ff.png)

The launcher does not support multi profiles.
Make sure you have **only** one player on your Blessing Skin instance and login with your email.

Install 「Single Player Limitation」 Plugin to enforce each user can own only one player.

**Comment by Aeris1One** [comment]
Thanks, I installed Single Player Limitation and it works !
