### ISSUE TITLE
[正版验证][功能请求]让FastLogin插件与正版验证互通

### ISSUE THREAD

**Issue by ahdg6** [bs-community/blessing-skin-plugins#72]
当在皮肤站正版验证成功后，往[FastLogin](https://github.com/games647/FastLogin)数据表添加相关记录，以让FastLogin在游戏中将玩家自动标记为正版玩家

谢谢

**Comment by tnqzh123** [comment]
为什么不直接用 authlib-injector 外置登录呢？

**Comment by ahdg6** [comment]
因为开的是mod服，部分mod(如FTBU)不兼容authlib-injector 外置登录，而且已经开了一段时间，转移数据成本略高。
希望大佬们能考虑添加一下这个功能，谢谢。

**Comment by tnqzh123** [comment]
FTBU 的问题这边已经反馈到 authlib-injector。如果还有什么 Mod 有问题，也请一并列出来。

大部分插件和 Mod 应该都还是按 UUID 来认人的，改一下 UUID 算法就可以兼容盗版。

这边改起来也比较麻烦，因为这边对 FastLogin 的数据表结构并不熟悉，而且相比于仅同步正版信息，再写一个数据对接插件大概都更方便。能用现成方案的我觉得就先用现成方案。当然，这边也欢迎相关 PR。

**Comment by ahdg6** [comment]
其实 FastLogin 的数据表结构和 插件正版验证 的表结构很相似,只需要在验证后往fastlogin数据表写入uuid,Name, Premium = 1，别的列留为null,就可以达到目的了
正版验证插件字段:![图片](https://user-images.githubusercontent.com/36436808/88409364-6dc5e480-ce07-11ea-985d-2d35f2dd993f.png)
FastLogin数据表字段:![图片](https://user-images.githubusercontent.com/36436808/88409562-afef2600-ce07-11ea-9552-d9ebb5c64440.png)

感谢大佬的耐心回答，但还是期待大佬能在空闲时随便写写来实现这个功能
