### ISSUE TITLE
yggdrasil api 正版验证无法进入服务器

### ISSUE THREAD

**Issue by Alice-space** [bs-community/blessing-skin-plugins#77]
今天实验发现，正版启动器无法直接加入使用authlib-injector的服务器，此前该正版账号已经在皮肤站做了正版验证。会提示“failed to verify username”
今后的版本是否可以正版玩家在皮肤站验证后直接加入authlib服务器，或许可以参考
[YggdrasilOfficialProxy](https://github.com/YggdrasilOfficialProxy/YggdrasilOfficialProxy)的实现原理

**Comment by Alice-space** [comment]
那就只能用YggdrasilOfficialProxy来实现任意启动器正版和盗版并存

**Comment by tnqzh123** [comment]
BS 和 AI 本身就没有所谓「在游戏中正盗版并存」的设计。

**Comment by g-plane** [comment]
正版用户加个 authlib-injector 就是了。

**Comment by Alice-space** [comment]
thx
