### ISSUE TITLE
部分插件无法成功安装

### ISSUE THREAD

**Issue by kimven** [bs-community/blessing-skin-plugins#79]
- [ ] 
![Screenshot_20200907-204124_Samsung Internet](https://user-images.githubusercontent.com/67876359/92417521-3c299280-f195-11ea-8430-6f3c65495951.jpg)

**Comment by kimven** [comment]
@g-plane

**Comment by g-plane** [comment]
现在试试？

**Comment by g-plane** [comment]
现在试试？

**Comment by kimven** [comment]
> 现在试试？
好了，谢谢作者
![Screenshot_20200911-205110_Samsung Internet](https://user-images.githubusercontent.com/67876359/92927739-ae89c380-f470-11ea-94ef-152d5434090c.jpg)

**Comment by g-plane** [comment]
我不是作者。
