### ISSUE TITLE
论坛同步插件完数据库信息之后无法登录

### ISSUE THREAD

**Issue by kimven** [bs-community/blessing-skin-plugins#80]
报错如图
![-a862db6069a1c9a](https://user-images.githubusercontent.com/67876359/93020456-be8bd980-f60f-11ea-8543-2f17ce9365aa.png)
等待大佬支援 @g-plane

**Comment by kimven** [comment]
@g-plane 咋回事啊大佬。。

**Comment by tnqzh123** [comment]
@kimven 不要急。

不是所有人都是 24hrs 在线，大家都有自己的生活。

如果确实需要立即处理，建议暂时停用论坛数据对接。
