### ISSUE TITLE
Yggdrasil api 登录后 皮肤不显示

### ISSUE THREAD

**Issue by luluxiaoyu** [bs-community/blessing-skin-plugins#84]
## The Problem 问题描述
使用nginx后，Yggdrasil  的皮肤在游戏内无法加载，但是按照常见问题中的访问url可以加载皮肤图片（之前使用apache没有这个问题）

## Environment 运行环境

**Blessing Skin**
版本	5.0.0
应用环境	production
是否处于调试状态	No
Laravel 版本	7.18.0
**服务器**
PHP 版本	7.4.11
Web 服务软件	nginx/1.18.0
操作系统	Linux 3.10.0-957.27.2.el7.x86_64 x86_64

## Error Message 错误信息
无

## Steps to Reproduce 重现步骤
使用nginx

**Comment by g-plane** [comment]
有没有使用 CDN 之类的？

**Comment by luluxiaoyu** [comment]
没有，域名直接解析到服务器的

**Comment by g-plane** [comment]
那检查你的 Nginx 配置，看看有没有对 PNG 文件加了什么规则。如果有，请进行调整或删除。

**Comment by luluxiaoyu** [comment]
nginx配置我已经修改为
    location ~ .*\.(gif|jpeg|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log /dev/null;
    }
了

**Comment by g-plane** [comment]
你确定这个配置有生效吗？例如，改动的地方是不是对应该 HTTP 服务，以及有没有重新加载配置文件。

**Comment by luluxiaoyu** [comment]
哦，好像是配置没生效
解决了，谢谢！
