### ISSUE TITLE
插件「批量导入」失败

### ISSUE THREAD

**Issue by older-fox** [bs-community/blessing-skin-plugins#88]
![image](https://user-images.githubusercontent.com/34577787/106215676-72cb7c80-620c-11eb-8f0e-fc35cfe7bab0.png)
在批量导入时出现错误
图片无法上传，我贴日志在下面

[root@olderfox t]# clear
[root@olderfox t]# php artisan texture:import 1 /www/wwwroot/skin.aliserver.net/upload/Skins/alex/
    0/7174 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%libpng warning: iCCP: known incorrect sRGB profile
  401/7174 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   5%libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: CRC error
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
  718/7174 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
 1435/7174 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
 1906/7174 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  26%libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
 2153/7174 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: Interlace handling should be turned on when using png_read_image
 2362/7174 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]  32%libpng warning: iCCP: known incorrect sRGB profile
 2631/7174 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  36%libpng warning: iCCP: known incorrect sRGB profile
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: tEXt: CRC error
 2870/7174 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%libpng warning: iCCP: known incorrect sRGB profile

   Symfony\Component\ErrorHandler\Error\FatalError

  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes)

  at vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:32
    28|         // define core
    29|         switch (strtolower($mime)) {
    30|             case 'image/png':
    31|             case 'image/x-png':
  > 32|                 $core = @imagecreatefrompng($path);
    33|                 break;
    34|
    35|             case 'image/jpg':
    36|             case 'image/jpeg':

[root@olderfox ]#

**Comment by g-plane** [comment]
这是因为材质在被导入的过程中，需要读取材质文件以便判断是 Steve 模型还是 Alex 模型。而这里应该是材质文件太大导致内存溢出。

**Comment by older-fox** [comment]
> 这是因为材质在被导入的过程中，需要读取材质文件以便判断是 Steve 模型还是 Alex 模型。而这里应该是材质文件太大导致内存溢出。

意见：能否提前检测文件尺寸及文件属性，以防止溢出问题
另外，能否加入纯色检测，某些背景为纯色或不透明的皮肤会导致误识别为Steve皮肤，导致手臂出现纯色条。
意见是首先读取右下角的颜色作为检测基准值，后检测Alex与Steve的不同区域，这样更为精准。

**Comment by older-fox** [comment]
另外，对于png格式不精准的图片文件，能否进行事先的转换操作以规避错误报告

**Comment by g-plane** [comment]
这些过程太复杂，不是「材质导入」应该做的。

**Comment by older-fox** [comment]
> 这些过程太复杂，不是「材质导入」插件应该做的。
那么对于材质转换插件，以上修复意见能采纳嘛？

**Comment by g-plane** [comment]
可以考虑。

**Comment by g-plane** [comment]
你的材质中有大小达到甚至超过几十 MB 的吗？
