### ISSUE TITLE
启用 Authme 数据对接之后莫名重复添加角色

### ISSUE THREAD

**Issue by misaka00251** [bs-community/blessing-skin-plugins#89]
![image](https://user-images.githubusercontent.com/3908746/106478658-5ff2c980-64e4-11eb-821b-5465d88d9cc4.png)

在服务器内无任何角色的情况下，添加角色。此时，只有一条角色记录。但在插件管理内开启 Authme 插件之后，大概 1 秒钟就会重复生成一次。此问题在 Minecraft 服务端本体未开启时也会出现。

**Comment by EdisonJwa** [comment]
更新到最新版本的Authme 数据对接后遇到同样问题

**Comment by Shizuri23** [comment]
刚刚更新的
![image](https://user-images.githubusercontent.com/46082179/109463010-4b7ffd80-7a9f-11eb-8dad-38e15d19ce4d.png)
也是这样

**Comment by ddaodan** [comment]
同样问题，我就惨多了，700多个用户，数据库直接炸了
![image](https://user-images.githubusercontent.com/40017293/109474359-6490aa80-7aaf-11eb-8c11-2cd304966e22.png)
