### ISSUE TITLE
启用yggdrasil-api后，角色重命名，游戏内用户数据会清空，并重新生成UUID

### ISSUE THREAD

**Issue by Chenjinyi** [bs-community/blessing-skin-plugins#9]
用户只要未进入服务器便不会生成UUID/
用户重命名后进入服务器UUID重新生成，导致游戏内数据重置

**Comment by printempw** [comment]
重命名？是指用户修改角色名后 UUID 也跟着改变的意思？

**Comment by Chenjinyi** [comment]
嗯，是的

**Comment by printempw** [comment]
有安装「单角色限制」插件么？

**Comment by Chenjinyi** [comment]
没有，这插件我好像没找到，阔以提供一下地址我再研究一下吗

**Comment by printempw** [comment]
没事，不装也没问题（地址在 [这里](https://coding.net/u/printempw/p/bs-plugins-archive/git/blob/master/single-player-limit_v1.0.5.zip)）。

问题我了解了，明天修复。

**Comment by Chenjinyi** [comment]
OK，麻烦了，还有我注意到只有用户在游戏客户端登陆才会生成UUID

**Comment by printempw** [comment]
事实上确实是这样的

https://github.com/bs-community/yggdrasil-api/blob/master/src/Models/Profile.php#L111

**Comment by printempw** [comment]
啊，不小心 close 掉了，抱歉。

你用 https://github.com/bs-community/yggdrasil-api/blob/master/bootstrap.php 这个文件覆盖掉 `yggdrasil-api` 插件里的同名文件，试试看问题有没有修复？

**Comment by Chenjinyi** [comment]
更新之后，确实修复了UUID这个BUG
就是开启单角色限制后原用户的UUID会被全部删除，
以及在更新bootstrap.php的之后不开启单皮肤插件会爆错（注释该代码后前往后台开启单角色限制便不会出现此报错）
（致谢）
![image](https://user-images.githubusercontent.com/24617962/43359726-d41ff34e-92d9-11e8-98f9-b611a7df2bc5.png)

**Comment by printempw** [comment]
Bug 了解了。不过开启「单角色限制」插件虽然会删除用户除了当前绑定角色外的其他角色，但是照理来说应该是不会删除 UUID 映射的啊？

尝试把报错的那一行修改为（不要注释掉 else）：

```
if (plugin('single-player-limit') && plugin('single-player-limit')->isEnabled()) {
```

**Comment by Chenjinyi** [comment]
我是先开启单角色限制的，然后关闭之后uuid表就没了

**Comment by printempw** [comment]
不可能啊……你现在还能复现么？

**Comment by Chenjinyi** [comment]
神秘，阔能大半夜见鬼了。ojbk，我可以愉快的写插件去了

**Comment by printempw** [comment]
你插件配置里的「UUID 生成算法」选的是什么？随机生成还是使用和盗版相同的生成算法？

毕竟后者要最大限度兼容盗版模式，所以我在考虑仅在选择「随机生成 UUID 算法」时让角色重命名后 UUID 仍可保持不变。
