### ISSUE TITLE
v6.0.0 Beta无法正常工作

### ISSUE THREAD

**Issue by TGCyrus** [bs-community/blessing-skin-plugins#90]
## The Problem 问题描述
在v6.0.0 Beta中，Yggdrasil API貌似无法正常工作。我不知道是我的原因还是新版本的原因甚至是插件的原因
## Environment 运行环境

- Blessing Skin 版本 (Version of Blessing Skin):v6.0.0 Beta-1 2021/1/15 Version
- PHP 版本 (Version of PHP):7.4
- Apache / Nginx:Apache
- 什么浏览器，出现错误时的地址栏 URL 是什么 (Which browser and URL):

## Error Message 错误信息

Minecraft启动器直接弹出无法解析服务器，皮肤站已经搭建完毕可以正常使用

## Steps to Reproduce 重现步骤

安装宝塔面板
安装必备组件，例如php7.4，Apache
开启必要的函数，关闭防跨站安全设置
下载blessing-skin-server-v6.0.0.zip
上传到主机
解压操作后设置根目录
设置数据库
.env.example重命名
生成appkey
安装Blessing Skin Server
在皮肤站装载必要插件，例如Yggdrasil API
打开启动器
认证服务器API成功
输入账号密码
！！弹出错误信息！！无法解析服务器响应，可能是服务器故障

**Comment by g-plane** [comment]
以后插件的问题，请在插件仓库提 issue。

你有没有把插件更新到 5.0.0 版本？

**Comment by TGCyrus** [comment]
插件已经是5.0.0版本

**Comment by g-plane** [comment]
那请你提供日志。

**Comment by TGCyrus** [comment]
我是发现Ygg api在5.2.0用不了的时候，重置服务器，使用的v6.0.0

**Comment by TGCyrus** [comment]
好的，请问日志在哪里？

**Comment by TGCyrus** [comment]
我这里并非启动服务器，而是客户端问题呀..

**Comment by g-plane** [comment]
日志文件在 storage/logs/laravel.log。请注意把日志文件根据需要来节选并上传在 pastebin，不要直接贴在这里，以免影响阅读。

**Comment by TGCyrus** [comment]
pastebin网址为https://paste.ubuntu.com/p/9W9b9nzQFs/

**Comment by TGCyrus** [comment]
请问您是否看见？

**Comment by g-plane** [comment]
看得到，我晚些再分析。

**Comment by TGCyrus** [comment]
好的

**Comment by TGCyrus** [comment]
请问您大约什么时候可以分析？

**Comment by g-plane** [comment]
我暂时没有空，请不要催。

**Comment by TGCyrus** [comment]
好的

**Comment by g-plane** [comment]
在你的 `.env` 文件里，看看有没有 `JWT_SECRET` 这一条并且值是不是一条比较长的字符串？

**Comment by TGCyrus** [comment]
在我的.env文件中没有看见JWT_SECRET这个值

**Comment by TGCyrus** [comment]
.env文件如下
https://paste.ubuntu.com/p/cJQSvVst36/

**Comment by TGCyrus** [comment]
您还在吗？

**Comment by tnqzh123** [comment]
@TGCyrus Issue 不是即时通讯，它更像是论坛，开发者不会一直盯着，更别说别人还有自己的事要做。

你的每一个回复，都会被通过邮件推送给所有 Watch 了这个项目的人，所以，为了减少不必要的打扰，请尽量减少不必要的回复。

如果你对时效性有比较高的要求，建议加入我们的 Telegram 群组进行讨论。

**Comment by Restent** [comment]
@TGCyrus Discord 群组：https://discord.gg/89QSwZy
Telegram 群组：https://t.me/blessing_skin

**Comment by TGCyrus** [comment]
您好，Blessing Skin Server的开发者
我刚刚在.env文件中新建了一条规则
JWT_SECRET="APP_KEY生成的key"
然后再用启动器登录就可以访问了

我不知道这是巧合还是一个变量？如果您对Blessing Skin Server中的JWT_SECRET值有特殊规定要求，我会立马更改
不麻烦您了，感谢您的回帖~再见
