### ISSUE TITLE
更新插件后导致functions.php文件丢失

### ISSUE THREAD

**Issue by older-fox** [bs-community/blessing-skin-plugins#91]
如标题描述，更新插件后OAuthCore似乎出现了问题导致全站无法访问
以下是问题详细内容及Debug开启后的截图

![image](https://user-images.githubusercontent.com/34577787/108612220-6b6d4c80-7421-11eb-8314-bb594a46e295.png)
![image](https://user-images.githubusercontent.com/34577787/108612248-9657a080-7421-11eb-9e69-737dd8b5f95d.png)

**Comment by older-fox** [comment]
补充：似乎artisan也失效了
![image](https://user-images.githubusercontent.com/34577787/108612278-09611700-7422-11eb-81f1-906922efb134.png)

**Comment by jared2021-cn** [comment]
同样遇到了该问题

**Comment by jared2021-cn** [comment]
将版本升级为v6解决问题

**Comment by mochaaP** [comment]
看起来已解决，故关闭。
