### ISSUE TITLE
启用Yggdrasil API时报错

### ISSUE THREAD

**Issue by HateRei** [bs-community/blessing-skin-plugins#93]
![image](https://user-images.githubusercontent.com/64119563/109422691-96eec900-7a17-11eb-8aeb-6b83647e0ab8.png)

**Comment by Aeris1One** [comment]
After reinstalling Yggdrasil-API because of #95 had this error

**Comment by Aeris1One** [comment]
Can I just bump the issue because is something very annoying when trying to setup a Yggdrasil server
