### ISSUE TITLE
Yggdrasil-API - Lcobucci bug

### ISSUE THREAD

**Issue by Aeris1One** [bs-community/blessing-skin-plugins#95]
![image](https://user-images.githubusercontent.com/29739547/112505055-b239c380-8d8c-11eb-9e5f-eb0bd383c365.png)

**Comment by RookiesTwo** [comment]
这边也有相似报错`
[2021-03-28 00:20:47] production.ERROR: Argument 1 passed to Lcobucci\JWT\Signer\Key\InMemory::plainText() must be of the type string, null given, called in C:\Wheat\BlessingSkin\plugins\yggdrasil-api\src\Controllers\AuthController.php on line 37 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Lcobucci\\JWT\\Signer\\Key\\InMemory::plainText() must be of the type string, null given, called in C:\\Wheat\\BlessingSkin\\plugins\\yggdrasil-api\\src\\Controllers\\AuthController.php on line 37 at C:\\Wheat\\BlessingSkin\\vendor\\lcobucci\\jwt\\src\\Signer\\Key\\InMemory.php:31)
[stacktrace]
#0 C:\\Wheat\\BlessingSkin\\plugins\\yggdrasil-api\\src\\Controllers\\AuthController.php(37): Lcobucci\\JWT\\Signer\\Key\\InMemory::plainText(NULL)
#1 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): Yggdrasil\\Controllers\\AuthController->authenticate(Object(Illuminate\\Http\\Request))
#2 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('authenticate', Array)
#3 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Yggdrasil\\Controllers\\AuthController), 'authenticate')
#4 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#5 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(693): Illuminate\\Routing\\Route->run()
#6 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 C:\\Wheat\\BlessingSkin\\plugins\\yggdrasil-api\\src\\Middleware\\Throttle.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Yggdrasil\\Middleware\\Throttle->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 C:\\Wheat\\BlessingSkin\\plugins\\yggdrasil-api\\src\\Middleware\\CheckContentType.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Yggdrasil\\Middleware\\CheckContentType->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\Wheat\\BlessingSkin\\plugins\\yggdrasil-api\\src\\Middleware\\AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\Wheat\\BlessingSkin\\app\\Http\\Middleware\\DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\Wheat\\BlessingSkin\\app\\Http\\Middleware\\ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 C:\\Wheat\\BlessingSkin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#32 C:\\Wheat\\BlessingSkin\\public\\index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#33 {main}
"}`

使用Apache2.4.46
PHP 7.4.9
MySQL 5.7.31
在windows server 2016运行
HMCL提示：“无法解析认证服务器响应，可能是服务器故障”
发生于尝试使用authlib-injector登录时

**Comment by Aeris1One** [comment]
This issue is a direct consequence of #93
