### ISSUE TITLE
第三方(微软microsoft live)登录账号无法登录外置登录

### ISSUE THREAD

**Issue by TvsAECC** [bs-community/blessing-skin-plugins#99]
microsoft live 登录已经配置好可以使用微软账户(已购买正版)登录到皮肤站.
但是无法使用外置登录去登录启动器.
我尝试过个人中心的首页`正版绑定`,提示密码错误.

![](https://i.postimg.cc/nhWV7MdQ/140236.png)

我尝试另外一个mojang 正版账号是可以通过直接登录到皮肤站而且通过外置登录启动器也是没有问题的.

---

版本:`6.0.0-beta.2`

已装插件

1. OAuth 客户端核心插件
2. Yggdrasil API
3. 正版验证
4. 使用 Microsoft Live 登录

**Comment by Asnxthaony** [comment]
「正版绑定」插件目前仅支持绑定 Mojang 帐户
启动器登录时，应使用你在皮肤站中使用的用户名及密码（注册页面通过第三方注册，默认无密码，需要使用「重置密码」来设定密码）

**Comment by TvsAECC** [comment]
> 「正版绑定」插件目前仅支持绑定 Mojang 帐户
> 启动器登录时，应使用你在皮肤站中使用的用户名及密码（注册页面通过第三方注册，默认无密码，需要使用「重置密码」来设定密码）

嗯.`正版绑定`的问题我知道我也理解.

主要是 `第三方登录` 账号 无法使用外置登录.

**Comment by TvsAECC** [comment]
> 「正版绑定」插件目前仅支持绑定 Mojang 帐户
> 启动器登录时，应使用你在皮肤站中使用的用户名及密码（注册页面通过第三方注册，默认无密码，需要使用「重置密码」来设定密码）

`第三方登录` 插件创建的账号因为是使用微软的oauth来登录.所以外置登录启动器的时候填写的密码也是微软的密码.所以才会造成这个问题.皮肤站肯定不认. 不知道如何解决这个问题.

**Comment by Asnxthaony** [comment]
> > 「正版绑定」插件目前仅支持绑定 Mojang 帐户
> > 启动器登录时，应使用你在皮肤站中使用的用户名及密码（注册页面通过第三方注册，默认无密码，需要使用「重置密码」来设定密码）
> 
> `第三方登录` 插件创建的账号因为是使用微软的oauth来登录.所以外置登录启动器的时候填写的密码也是微软的密码.所以才会造成这个问题.皮肤站肯定不认. 不知道如何解决这个问题.

此类帐号默认无密码，可登出帐号，并在点击登录页中的「忘记密码」重设密码
